# Generated by Django 2.2.7 on 2019-12-13 16:38

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('todolist', '0004_auto_20191213_1632'),
    ]

    operations = [
        migrations.AlterField(
            model_name='todoitem',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='todoitemarchived',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
