# Generated by Django 2.2.7 on 2019-12-13 16:57

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('todolist', '0005_auto_20191213_1638'),
    ]

    operations = [
        migrations.CreateModel(
            name='TodoItemLogger',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField()),
                ('action', models.CharField(choices=[('A', 'Added'), ('D', 'Deleted'), ('U', 'Updated')], max_length=1)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
